version: "3"
networks:
  kafka-network:
    driver: bridge
services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-network
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092, EXTERNAL://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper  
  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    networks:
      - kafka-network
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092  
    depends_on:
      - zookeeper
      - kafka
  mongodb1:
    container_name: mongodb1
    image: 'mongo:5.0'
    expose:
      - 27017
    ports:
      - '27017:27017'
    networks:
      - kafka-network  
    command: --replSet local-mongodb-replica-set --bind_ip_all  
  mongodb2:
    container_name: mongodb2
    image: 'mongo:5.0'
    expose:
      - 27017  
    ports:
      - '27018:27017'
    networks:
      - kafka-network  
    command: --replSet local-mongodb-replica-set --bind_ip_all 
  connect:
    container_name: connect
    image: 'quay.io/debezium/connect:1.9'
    networks:
      - kafka-network
    ports:
      - '8083:8083'  
    environment:
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - BOOTSTRAP_SERVERS=kafka:9092
    links:
      - "zookeeper:zookeeper"
      - "kafka:kafka"
      - "mongodb1:mongodb1"  
      - "mongodb2:mongodb2"  
    depends_on:
      - zookeeper
      - kafka   
      - mongodb1
      - mongodb2


      # IMPORTANT add to hosts file 127.0.0.1 mongodb1 mongodb2

      #https://debezium.io/documentation/reference/tutorial.html
      #https://hub.docker.com/_/mongo
      #https://debezium.io/documentation/reference/stable/connectors/mongodb.html#mongodb-adding-connector-configuration
      #https://www.sohamkamani.com/blog/2016/06/30/docker-mongo-replica-set/
      #https://gist.github.com/harveyconnor/518e088bad23a273cae6ba7fc4643549




